// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function AddItem(arg1:number,arg2:string,arg3:number,arg4:string):Promise<main.Item>;

export function AddSale(arg1:number,arg2:number):Promise<main.Transaction>;

export function AddTransaction(arg1:main.Transaction):Promise<main.Transaction>;

export function DeleteActivity(arg1:number):Promise<void>;

export function DeleteItem(arg1:number):Promise<void>;

export function DeleteTransaction(arg1:number):Promise<void>;

export function FinishItem(arg1:number,arg2:number):Promise<void>;

export function GetActivity(arg1:number):Promise<main.ActivityWithStats>;

export function GetSummary():Promise<main.Summary>;

export function ListActivities():Promise<Array<main.ActivityWithStats>>;

export function ListItems(arg1:number):Promise<Array<main.ItemWithStats>>;

export function ListTransactions():Promise<Array<main.Transaction>>;

export function ListTransactionsByActivity(arg1:number):Promise<Array<main.Transaction>>;

export function SearchDofusItems(arg1:string):Promise<Array<main.DofusItem>>;

export function UpdateTransaction(arg1:main.Transaction):Promise<main.Transaction>;
