// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function AddTransaction(arg1:main.Transaction):Promise<main.Transaction>;

export function DeleteTransaction(arg1:number):Promise<void>;

export function GetSummary():Promise<main.Summary>;

export function ListTransactions():Promise<Array<main.Transaction>>;
