// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddItem(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['AddItem'](arg1, arg2, arg3, arg4);
}

export function AddSale(arg1, arg2) {
  return window['go']['main']['App']['AddSale'](arg1, arg2);
}

export function AddTransaction(arg1) {
  return window['go']['main']['App']['AddTransaction'](arg1);
}

export function DeleteActivity(arg1) {
  return window['go']['main']['App']['DeleteActivity'](arg1);
}

export function DeleteItem(arg1) {
  return window['go']['main']['App']['DeleteItem'](arg1);
}

export function DeleteTransaction(arg1) {
  return window['go']['main']['App']['DeleteTransaction'](arg1);
}

export function FinishItem(arg1, arg2) {
  return window['go']['main']['App']['FinishItem'](arg1, arg2);
}

export function GetActivity(arg1) {
  return window['go']['main']['App']['GetActivity'](arg1);
}

export function GetSummary() {
  return window['go']['main']['App']['GetSummary']();
}

export function ListActivities() {
  return window['go']['main']['App']['ListActivities']();
}

export function ListItems(arg1) {
  return window['go']['main']['App']['ListItems'](arg1);
}

export function ListTransactions() {
  return window['go']['main']['App']['ListTransactions']();
}

export function ListTransactionsByActivity(arg1) {
  return window['go']['main']['App']['ListTransactionsByActivity'](arg1);
}

export function SearchDofusItems(arg1) {
  return window['go']['main']['App']['SearchDofusItems'](arg1);
}

export function UpdateTransaction(arg1) {
  return window['go']['main']['App']['UpdateTransaction'](arg1);
}
